name: Build and Publish testblazor Image

on:
  push:
    branches: ["main"]
  workflow_dispatch:

env:
  REGISTRY: ghcr.io

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up .NET SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.x

      - name: Set environment variables
        id: set-variables
        run: |
          VERSION=$(grep -oP '<ContainerImageTag>\K[^<]+'  testblazor.csproj || echo "1.0.0")
          echo "VERSION=$VERSION" >> "$GITHUB_ENV"

      - name: Publish testblazor
        run: dotnet publish testblazor --os linux --arch x64 -c Release /p:PublishProfile=DefaultContainer /p:ContainerImageTag=${{ env.VERSION }}

      - name: Tag Docker Image
        run: |
          docker tag testblazor:${{ env.VERSION }} ${{ env.REGISTRY }}/${{ github.actor }}/testblazor:${{ env.VERSION }}
          docker tag testblazor:latest ${{ env.REGISTRY }}/${{ github.actor }}/testblazor:latest

      - name: Docker Login
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.PAT }}

      - name: Push Docker Image to GHCR
        run: docker push -a ${{ env.REGISTRY }}/${{ github.actor }}/testblazor

      - name: Verify Image in GHCR
        run: |
          echo "Image pushed to: ${{ env.REGISTRY }}/${{ github.actor }}/testblazor:${{ env.VERSION }}"
          docker images | grep testblazor
